import AppKit
import Carbon.HIToolbox

/// 剪贴板历史：在后台记录复制过的文本、图片和文件，供随 App 内置的「剪贴板」扩展页面使用
/// （spotcat.clipboard.*，需要 "clipboard" 权限）。只在该扩展启用时运行。
/// 数据在 ~/Library/Application Support/Spotcat/Clipboard/
final class ClipboardHistory {
    static let shared = ClipboardHistory()
    /// 随 App 内置的剪贴板扩展（Resources/extensions/clipboard）
    static let extensionID = "clipboard"
    static let didChange = Notification.Name("SpotcatClipboardHistoryDidChange")

    struct Entry: Codable {
        enum Kind: String, Codable { case text, image, files }

        let id: String
        let kind: Kind
        var text: String?
        var files: [String]?
        /// 图片文件名（images/ 目录下）
        var image: String?
        var imageWidth: Int?
        var imageHeight: Int?
        /// 复制时的前台应用
        var app: String?
        var appBundleID: String?
        var date: Date
        var pinned: Bool
    }

    private static let maxEntries = 1000
    private static let maxImages = 100
    private static let maxTextLength = 200_000
    private static let pollInterval: TimeInterval = 0.5

    /// 密码管理器等用这些类型标记不应被记录的内容（nspasteboard.org）
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType",
    ]

    private(set) var entries: [Entry] = []
    private var timer: Timer?
    private let pasteboard: NSPasteboard
    private var lastChangeCount: Int
    private var saveScheduled = false
    private let thumbnails = NSCache<NSString, NSString>()

    private let directory: URL
    private var imagesDirectory: URL { directory.appendingPathComponent("images", isDirectory: true) }
    private var historyURL: URL { directory.appendingPathComponent("history.json") }

    /// 参数用于测试：换成独立的剪贴板和目录，不碰用户的数据
    init(pasteboard: NSPasteboard = .general,
         directory: URL = AppEnvironment.dataDirectory.appendingPathComponent("Clipboard", isDirectory: true)) {
        self.pasteboard = pasteboard
        self.directory = directory
        lastChangeCount = pasteboard.changeCount
        if let data = try? Data(contentsOf: historyURL) {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .millisecondsSince1970
            entries = (try? decoder.decode([Entry].self, from: data)) ?? []
        }
    }

    var isActive: Bool { timer != nil }

    func setActive(_ active: Bool) {
        guard active != isActive else { return }
        if active {
            // 启动前复制的内容不算
            lastChangeCount = pasteboard.changeCount
            let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in self?.poll() }
            timer.tolerance = 0.2
            RunLoop.main.add(timer, forMode: .common)
            self.timer = timer
        } else {
            timer?.invalidate()
            timer = nil
        }
    }

    // MARK: - 采集

    func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes) else { return }
        let front = NSWorkspace.shared.frontmostApplication
        let app = front?.localizedName
        let bundleID = front?.bundleIdentifier

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            add(matching: { $0.kind == .files && $0.files == paths }) {
                Entry(id: Self.newID(), kind: .files, files: paths, app: app, appBundleID: bundleID, date: Date(), pinned: false)
            }
        } else if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let text = String(text.prefix(Self.maxTextLength))
            add(matching: { $0.kind == .text && $0.text == text }) {
                Entry(id: Self.newID(), kind: .text, text: text, app: app, appBundleID: bundleID, date: Date(), pinned: false)
            }
        } else if let image = NSImage(pasteboard: pasteboard), let png = Self.pngData(image) {
            let id = Self.newID()
            let name = "\(id).png"
            do {
                try FileManager.default.createDirectory(at: imagesDirectory, withIntermediateDirectories: true)
                try png.data.write(to: imagesDirectory.appendingPathComponent(name))
            } catch {
                return NSLog("%@", "Spotcat: 保存剪贴板图片失败：\(error)")
            }
            add(matching: { _ in false }) {
                Entry(id: id, kind: .image, image: name, imageWidth: png.width, imageHeight: png.height,
                      app: app, appBundleID: bundleID, date: Date(), pinned: false)
            }
        }
    }

    /// 已有相同内容时移到最前（保留置顶状态），否则新增
    private func add(matching isSame: (Entry) -> Bool, make: () -> Entry) {
        if let index = entries.firstIndex(where: isSame) {
            var entry = entries.remove(at: index)
            entry.date = Date()
            entries.insert(entry, at: 0)
        } else {
            entries.insert(make(), at: 0)
            trim()
        }
        changed()
    }

    /// 超出上限时删掉最旧的未置顶条目
    private func trim() {
        var images = 0
        var kept: [Entry] = []
        for entry in entries {
            if entry.kind == .image { images += 1 }
            let overLimit = kept.count >= Self.maxEntries || (entry.kind == .image && images > Self.maxImages)
            if overLimit && !entry.pinned {
                removeFiles(of: entry)
            } else {
                kept.append(entry)
            }
        }
        entries = kept
    }

    private static func newID() -> String {
        String(Int(Date().timeIntervalSince1970 * 1000), radix: 36) + String(Int.random(in: 0..<1_296), radix: 36)
    }

    private static func pngData(_ image: NSImage) -> (data: Data, width: Int, height: Int)? {
        guard let cg = image.cgImage(forProposedRect: nil, context: nil, hints: nil) else { return nil }
        let rep = NSBitmapImageRep(cgImage: cg)
        guard let data = rep.representation(using: .png, properties: [:]) else { return nil }
        return (data, cg.width, cg.height)
    }

    // MARK: - 操作

    func entry(id: String) -> Entry? {
        entries.first { $0.id == id }
    }

    /// 写回剪贴板并移到最前；不会被当成新复制再记录一次
    @discardableResult
    func copy(id: String) -> Bool {
        guard let index = entries.firstIndex(where: { $0.id == id }) else { return false }
        let entry = entries[index]
        pasteboard.clearContents()
        switch entry.kind {
        case .text:
            pasteboard.setString(entry.text ?? "", forType: .string)
        case .files:
            pasteboard.writeObjects((entry.files ?? []).map { URL(fileURLWithPath: $0) as NSURL })
        case .image:
            guard let image = imageURL(entry).flatMap(NSImage.init(contentsOf:)) else { return false }
            pasteboard.writeObjects([image])
        }
        lastChangeCount = pasteboard.changeCount
        var moved = entries.remove(at: index)
        moved.date = Date()
        entries.insert(moved, at: 0)
        changed()
        return true
    }

    func setPinned(_ pinned: Bool, id: String) {
        guard let index = entries.firstIndex(where: { $0.id == id }) else { return }
        entries[index].pinned = pinned
        changed()
    }

    func remove(id: String) {
        guard let index = entries.firstIndex(where: { $0.id == id }) else { return }
        removeFiles(of: entries.remove(at: index))
        changed()
    }

    /// 清空未置顶的条目
    func clear() {
        entries.filter { !$0.pinned }.forEach(removeFiles)
        entries.removeAll { !$0.pinned }
        changed()
    }

    private func removeFiles(of entry: Entry) {
        if let url = imageURL(entry) { try? FileManager.default.removeItem(at: url) }
        thumbnails.removeObject(forKey: entry.id as NSString)
    }

    func imageURL(_ entry: Entry) -> URL? {
        entry.image.map { imagesDirectory.appendingPathComponent($0) }
    }

    /// 列表和预览用的缩略图（data URL），按需生成并缓存
    func thumbnail(for entry: Entry, maxSize: CGFloat = 480) -> String? {
        if let cached = thumbnails.object(forKey: entry.id as NSString) { return cached as String }
        guard let url = imageURL(entry), let image = NSImage(contentsOf: url),
              let cg = image.cgImage(forProposedRect: nil, context: nil, hints: nil) else { return nil }
        let scale = min(1, maxSize / CGFloat(max(cg.width, cg.height)))
        let size = NSSize(width: max(1, CGFloat(cg.width) * scale), height: max(1, CGFloat(cg.height) * scale))
        guard let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: Int(size.width), pixelsHigh: Int(size.height),
                                         bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
                                         colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0) else { return nil }
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
        NSGraphicsContext.current?.imageInterpolation = .high
        image.draw(in: NSRect(origin: .zero, size: size))
        NSGraphicsContext.restoreGraphicsState()
        guard let png = rep.representation(using: .png, properties: [:]) else { return nil }
        let dataURL = "data:image/png;base64," + png.base64EncodedString()
        thumbnails.setObject(dataURL as NSString, forKey: entry.id as NSString)
        return dataURL
    }

    // MARK: - 保存

    private func changed() {
        NotificationCenter.default.post(name: Self.didChange, object: self)
        guard !saveScheduled else { return }
        saveScheduled = true
        // 连续复制时合并写盘
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) { [weak self] in
            self?.saveScheduled = false
            self?.save()
        }
    }

    func save() {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .millisecondsSince1970
        do {
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            try encoder.encode(entries).write(to: historyURL, options: .atomic)
        } catch {
            NSLog("%@", "Spotcat: 保存剪贴板历史失败：\(error)")
        }
    }
}

/// 把剪贴板内容粘贴到前台应用：模拟 ⌘V，需要「辅助功能」权限。
/// 启动器是不激活 App 的面板，隐藏后键盘焦点自然回到原来的应用
enum Paster {
    /// 没有权限时弹出系统授权提示并返回 false（内容已经在剪贴板里，用户可以手动粘贴）
    static func paste() -> Bool {
        let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true] as CFDictionary
        guard AXIsProcessTrustedWithOptions(options) else { return false }
        // 等面板隐藏、焦点回到前台应用
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.08) {
            let source = CGEventSource(stateID: .combinedSessionState)
            let key = CGKeyCode(kVK_ANSI_V)
            let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
            let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
            down?.flags = .maskCommand
            up?.flags = .maskCommand
            down?.post(tap: .cghidEventTap)
            up?.post(tap: .cghidEventTap)
        }
        return true
    }
}
